### ISSUE TITLE
slakh dataset init error

### ISSUE THREAD

**Issue by ldzhangyx** [yoyololicon/music-spectrogram-diffusion-pytorch#54]
```
  File "/diffusion/data/slakh.py", line 184, in __init__
    sampled_numbers = sample(
TypeError: sample() got an unexpected keyword argument 'counts'
```

I think `random.sample()` does not contain a param called counts... what is the purpose?

**Comment by yoyololicon** [comment]
Hi @ldzhangyx,
I think it's a problem with your python version.
`counts` parameter was added in `random.sample` for python >= 3.9.

**Comment by ldzhangyx** [comment]
make sense. Let's move to Python 3.9.
